"""Website intake tables — schema ``public``, not ``crm``.

The marketing site posts its quotation form to ``/api/quote``, which inserts
into ``public.quotation_requests`` server-side with the Supabase secret key:

    Website -> /api/quote -> Supabase secret key -> public.quotation_requests

The CRM never inserts here. It reads the queue and moves a request through
``status`` / ``internal_notes`` / ``contacted_at`` — the three columns the
website deliberately leaves to trusted operators.

The DDL of record is ``supabase/sql/quotation_requests.sql``; the table lives
outside Alembic because it belongs to the website, not to the CRM schema. The
model is still declared on ``Base.metadata`` so autogenerate knows the table
exists and never proposes dropping it.
"""
import uuid
from datetime import datetime

from sqlalchemy import Boolean, String, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

# Mirrors the CHECK constraint on the table. 'new' is the DB default.
QUOTATION_REQUEST_STATUSES = (
    "new",
    "contacted",
    "quotation_preparing",
    "quotation_sent",
    "won",
    "lost",
    "closed",
)

# Statuses that mean somebody has already picked the request up.
OPEN_STATUSES = ("new", "contacted", "quotation_preparing", "quotation_sent")


class QuotationRequest(Base):
    __tablename__ = "quotation_requests"
    __table_args__ = {"schema": "public"}

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    # Generated by the database: MPSTT-YYYYMMDD-XXXXXX in Asia/Karachi time.
    reference: Mapped[str] = mapped_column(Text, nullable=False, unique=True)

    # --- submitted by the website form ---
    full_name: Mapped[str] = mapped_column(Text, nullable=False)
    organization: Mapped[str] = mapped_column(Text, nullable=False)
    phone: Mapped[str] = mapped_column(Text, nullable=False)
    email: Mapped[str | None] = mapped_column(Text)
    organization_type: Mapped[str | None] = mapped_column(Text)
    requirement: Mapped[str] = mapped_column(Text, nullable=False)
    consent: Mapped[bool] = mapped_column(Boolean, nullable=False)
    source_page: Mapped[str | None] = mapped_column(Text)
    product_slug: Mapped[str | None] = mapped_column(Text)
    category_slug: Mapped[str | None] = mapped_column(Text)
    product_name: Mapped[str | None] = mapped_column(Text)
    intent: Mapped[str | None] = mapped_column(Text)

    # --- owned by the CRM ---
    status: Mapped[str] = mapped_column(String, nullable=False, server_default=text("'new'"))
    internal_notes: Mapped[str | None] = mapped_column(Text)
    contacted_at: Mapped[datetime | None] = mapped_column()

    consent_at: Mapped[datetime] = mapped_column(server_default=text("now()"), nullable=False)
    created_at: Mapped[datetime] = mapped_column(server_default=text("now()"), nullable=False)
    # Maintained by the quotation_requests_set_updated_at trigger, not by us.
    updated_at: Mapped[datetime] = mapped_column(server_default=text("now()"), nullable=False)
