"""M1 access tables

Revision ID: 0002_m1_access
Revises: 0001_baseline
Create Date: 2026-08-26 01:51:55.679065
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002_m1_access'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=60), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='crm'
    )
    op.create_table('company_settings',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('ntn', sa.String(length=50), nullable=True),
    sa.Column('strn', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), server_default='PKR', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Karachi', nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('quotation_terms', sa.Text(), nullable=True),
    sa.Column('document_footer', sa.Text(), nullable=True),
    sa.Column('logo_document_id', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_company_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings')),
    schema='crm'
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'action', 'idempotency_key', name='uq_idem_user_action_key'),
    schema='crm'
    )
    op.create_table('number_sequences',
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('next_value', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('padding', sa.SmallInteger(), server_default=sa.text('4'), nullable=False),
    sa.PrimaryKeyConstraint('document_type', 'year', name=op.f('pk_number_sequences')),
    schema='crm'
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','user')", name=op.f('ck_user_profiles_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    schema='crm'
    )
    # ### end Alembic commands ###

    # FK to Supabase auth.users only where that schema exists (managed project).
    op.execute("""
        DO $$
        BEGIN
            IF to_regclass('auth.users') IS NOT NULL THEN
                ALTER TABLE crm.user_profiles
                    ADD CONSTRAINT fk_user_profiles_id_auth_users
                    FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # Audit log is append-only: reject UPDATE/DELETE at the database level.
    op.execute("""
        CREATE OR REPLACE FUNCTION crm.fn_audit_log_append_only()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'crm.audit_log is append-only';
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON crm.audit_log
        FOR EACH ROW EXECUTE FUNCTION crm.fn_audit_log_append_only();
    """)
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], schema="crm")
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], schema="crm")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON crm.audit_log")
    op.execute("DROP FUNCTION IF EXISTS crm.fn_audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles', schema='crm')
    op.drop_table('number_sequences', schema='crm')
    op.drop_table('idempotency_keys', schema='crm')
    op.drop_table('company_settings', schema='crm')
    op.drop_table('audit_log', schema='crm')
    # ### end Alembic commands ###
