"""M2 organizations and field sales

Revision ID: 0004_m2_prospects
Revises: 0003_m3_catalogue
Create Date: 2026-08-26 02:16:05.466560
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0004_m2_prospects'
down_revision: str | None = '0003_m3_catalogue'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('org_type', sa.String(length=20), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=20), server_default='prospect', nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_normalized', sa.String(length=20), nullable=True),
    sa.Column('ntn', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_status IN ('prospect','customer')", name=op.f('ck_organizations_lifecycle_valid')),
    sa.CheckConstraint("org_type IN ('hospital', 'clinic', 'laboratory', 'pharmacy', 'industry', 'ngo', 'government', 'other')", name=op.f('ck_organizations_org_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('org_code', name=op.f('uq_organizations_org_code')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_organizations_phone_normalized'), 'organizations', ['phone_normalized'], unique=False, schema='crm')
    op.create_index('ix_organizations_lifecycle', 'organizations', ['lifecycle_status', 'is_active'], unique=False, schema='crm')
    op.create_index('ix_organizations_name_trgm', 'organizations', [sa.literal_column('name gin_trgm_ops')], unique=False, schema='crm', postgresql_using='gin')
    op.create_table('customer_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('customer_since', sa.Date(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('billing_notes', sa.Text(), nullable=True),
    sa.Column('purchasing_notes', sa.Text(), nullable=True),
    sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_customer_profiles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_customer_profiles')),
    sa.UniqueConstraint('customer_code', name=op.f('uq_customer_profiles_customer_code')),
    schema='crm'
    )
    op.create_table('organization_branches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(length=150), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('route_cluster', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_organization_branches_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_branches')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_organization_branches_organization_id'), 'organization_branches', ['organization_id'], unique=False, schema='crm')
    op.create_table('prospect_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=30), server_default='targeted', nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('first_contact_date', sa.Date(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_summary', sa.String(length=300), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('deferred_reason', sa.Text(), nullable=True),
    sa.Column('reactivation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('targeted', 'visited', 'requirement_collected', 'sample_provided', 'quotation_sent', 'negotiation', 'lost', 'deferred', 'won')", name=op.f('ck_prospect_profiles_stage_valid')),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['crm.user_profiles.id'], name=op.f('fk_prospect_profiles_assigned_user_id_user_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_prospect_profiles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_prospect_profiles')),
    schema='crm'
    )
    op.create_table('tasks',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('task_type', sa.String(length=40), server_default='follow_up', nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('completion_outcome', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high')", name=op.f('ck_tasks_priority_valid')),
    sa.CheckConstraint("status IN ('open', 'done', 'cancelled')", name=op.f('ck_tasks_status_valid')),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['crm.user_profiles.id'], name=op.f('fk_tasks_assigned_user_id_user_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_tasks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_tasks_organization_id'), 'tasks', ['organization_id'], unique=False, schema='crm')
    op.create_index('ix_tasks_assignee_status_due', 'tasks', ['assigned_user_id', 'status', 'due_at'], unique=False, schema='crm')
    op.create_table('organization_contacts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('phone_primary', sa.String(length=50), nullable=True),
    sa.Column('phone_primary_normalized', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['crm.organization_branches.id'], name=op.f('fk_organization_contacts_branch_id_organization_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_organization_contacts_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_contacts')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_organization_contacts_organization_id'), 'organization_contacts', ['organization_id'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_organization_contacts_phone_primary_normalized'), 'organization_contacts', ['phone_primary_normalized'], unique=False, schema='crm')
    op.create_table('activities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('products_discussed', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('visit', 'call', 'whatsapp', 'email', 'meeting', 'follow_up')", name=op.f('ck_activities_type_valid')),
    sa.ForeignKeyConstraint(['contact_id'], ['crm.organization_contacts.id'], name=op.f('fk_activities_contact_id_organization_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_activities_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    schema='crm'
    )
    op.create_index('ix_activities_org_time', 'activities', ['organization_id', 'happened_at'], unique=False, schema='crm')
    op.create_table('organization_prices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('price_type', sa.String(length=20), server_default='quoted', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('uom_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("price_type IN ('quoted', 'agreed', 'list')", name=op.f('ck_organization_prices_price_type_valid')),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_organization_prices_unit_price_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_organization_prices_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_organization_prices_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_organization_prices_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['crm.units_of_measure.id'], name=op.f('fk_organization_prices_uom_id_units_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_prices')),
    schema='crm'
    )
    op.create_index('ix_org_prices_lookup', 'organization_prices', ['organization_id', 'product_id', 'product_variant_id', 'effective_from'], unique=False, schema='crm')
    op.create_table('organization_product_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('min_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('uom_id', sa.UUID(), nullable=True),
    sa.Column('current_supplier', sa.String(length=200), nullable=True),
    sa.Column('current_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('specification_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_organization_product_profiles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_organization_product_profiles_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_organization_product_profiles_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['crm.units_of_measure.id'], name=op.f('fk_organization_product_profiles_uom_id_units_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_product_profiles')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_organization_product_profiles_organization_id'), 'organization_product_profiles', ['organization_id'], unique=False, schema='crm')
    op.create_table('samples',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('uom_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receiver_name', sa.String(length=150), nullable=True),
    sa.Column('feedback_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='issued', nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('issued', 'feedback_received', 'converted', 'closed')", name=op.f('ck_samples_status_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_samples_quantity_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_samples_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_samples_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_samples_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['crm.units_of_measure.id'], name=op.f('fk_samples_uom_id_units_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_samples')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_samples_organization_id'), 'samples', ['organization_id'], unique=False, schema='crm')
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE VIEW crm.v_prospect_action_queue AS
        SELECT
            o.id AS organization_id,
            o.org_code,
            o.name,
            o.city,
            o.area,
            pp.stage,
            pp.assigned_user_id,
            pp.last_activity_at,
            pp.next_action_summary,
            t.next_task_due_at,
            COALESCE(t.open_task_count, 0) AS open_task_count,
            (COALESCE(t.open_task_count, 0) = 0) AS missing_next_action,
            (t.next_task_due_at IS NOT NULL AND t.next_task_due_at < now()) AS overdue,
            CASE WHEN pp.last_activity_at IS NULL THEN NULL
                 ELSE floor(EXTRACT(EPOCH FROM (now() - pp.last_activity_at)) / 86400)::int
            END AS days_since_last_activity
        FROM crm.organizations o
        JOIN crm.prospect_profiles pp ON pp.organization_id = o.id
        LEFT JOIN LATERAL (
            SELECT min(due_at) AS next_task_due_at, count(*) AS open_task_count
            FROM crm.tasks
            WHERE organization_id = o.id AND status = 'open'
        ) t ON true
        WHERE o.lifecycle_status = 'prospect'
          AND o.is_active
          AND pp.stage NOT IN ('lost', 'deferred', 'won');
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS crm.v_prospect_action_queue")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_samples_organization_id'), table_name='samples', schema='crm')
    op.drop_table('samples', schema='crm')
    op.drop_index(op.f('ix_crm_organization_product_profiles_organization_id'), table_name='organization_product_profiles', schema='crm')
    op.drop_table('organization_product_profiles', schema='crm')
    op.drop_index('ix_org_prices_lookup', table_name='organization_prices', schema='crm')
    op.drop_table('organization_prices', schema='crm')
    op.drop_index('ix_activities_org_time', table_name='activities', schema='crm')
    op.drop_table('activities', schema='crm')
    op.drop_index(op.f('ix_crm_organization_contacts_phone_primary_normalized'), table_name='organization_contacts', schema='crm')
    op.drop_index(op.f('ix_crm_organization_contacts_organization_id'), table_name='organization_contacts', schema='crm')
    op.drop_table('organization_contacts', schema='crm')
    op.drop_index('ix_tasks_assignee_status_due', table_name='tasks', schema='crm')
    op.drop_index(op.f('ix_crm_tasks_organization_id'), table_name='tasks', schema='crm')
    op.drop_table('tasks', schema='crm')
    op.drop_table('prospect_profiles', schema='crm')
    op.drop_index(op.f('ix_crm_organization_branches_organization_id'), table_name='organization_branches', schema='crm')
    op.drop_table('organization_branches', schema='crm')
    op.drop_table('customer_profiles', schema='crm')
    op.drop_index('ix_organizations_name_trgm', table_name='organizations', schema='crm', postgresql_using='gin')
    op.drop_index('ix_organizations_lifecycle', table_name='organizations', schema='crm')
    op.drop_index(op.f('ix_crm_organizations_phone_normalized'), table_name='organizations', schema='crm')
    op.drop_table('organizations', schema='crm')
    # ### end Alembic commands ###
