"""M4 sales orders

Revision ID: 0005_m4_orders
Revises: 0004_m2_prospects
Create Date: 2026-08-26 09:36:51.847533
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0005_m4_orders'
down_revision: str | None = '0004_m2_prospects'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('source_quotation_id', sa.UUID(), nullable=True),
    sa.Column('is_direct_po', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('customer_po_number', sa.String(length=100), nullable=True),
    sa.Column('customer_po_document_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=25), server_default='draft', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'preparing', 'ready', 'partially_delivered', 'fully_delivered', 'completed', 'cancelled')", name=op.f('ck_sales_orders_status_valid')),
    sa.ForeignKeyConstraint(['branch_id'], ['crm.organization_branches.id'], name=op.f('fk_sales_orders_branch_id_organization_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_sales_orders_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_sales_orders_order_number')),
    schema='crm'
    )
    op.create_index('ix_sales_orders_org_status', 'sales_orders', ['organization_id', 'status'], unique=False, schema='crm')
    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('specification_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name=op.f('ck_sales_order_items_discount_range')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_sales_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_sales_order_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['crm.sales_orders.id'], name=op.f('fk_sales_order_items_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_items')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_sales_order_items_sales_order_id'), 'sales_order_items', ['sales_order_id'], unique=False, schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_sales_order_items_sales_order_id'), table_name='sales_order_items', schema='crm')
    op.drop_table('sales_order_items', schema='crm')
    op.drop_index('ix_sales_orders_org_status', table_name='sales_orders', schema='crm')
    op.drop_table('sales_orders', schema='crm')
    # ### end Alembic commands ###
