"""M11 documents

Revision ID: 0006_m11_documents
Revises: 0005_m4_orders
Create Date: 2026-08-26 09:43:24.408793
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0006_m11_documents'
down_revision: str | None = '0005_m4_orders'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.String(length=40), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('retention_label', sa.String(length=40), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    schema='crm'
    )
    op.create_index('ix_documents_entity', 'documents', ['entity_type', 'entity_id'], unique=False, schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_entity', table_name='documents', schema='crm')
    op.drop_table('documents', schema='crm')
    # ### end Alembic commands ###
