"""M5 quotations

Revision ID: 0007_m5_quotations
Revises: 0006_m11_documents
Create Date: 2026-08-26 09:48:15.471893
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0007_m5_quotations'
down_revision: str | None = '0006_m11_documents'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_quotation_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('quote_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('pdf_document_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('converted_order_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'accepted', 'rejected', 'superseded', 'converted', 'cancelled')", name=op.f('ck_quotations_status_valid')),
    sa.CheckConstraint('revision_no >= 1', name=op.f('ck_quotations_revision_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['crm.organization_branches.id'], name=op.f('fk_quotations_branch_id_organization_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm.organization_contacts.id'], name=op.f('fk_quotations_contact_id_organization_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_quotations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_quotation_id'], ['crm.quotations.id'], name=op.f('fk_quotations_parent_quotation_id_quotations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('quotation_number', 'revision_no', name='uq_quote_number_revision'),
    schema='crm'
    )
    op.create_index('ix_quotations_org_status', 'quotations', ['organization_id', 'status'], unique=False, schema='crm')
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('specification_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name=op.f('ck_quotation_items_discount_range')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_quotation_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_quotation_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_quotation_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_quotation_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['crm.quotations.id'], name=op.f('fk_quotation_items_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_items')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False, schema='crm')
    # ### end Alembic commands ###

    # Late FK: sales_orders.source_quotation_id -> quotations (table exists now).
    op.create_foreign_key(
        "fk_sales_orders_source_quotation_id_quotations",
        "sales_orders", "quotations",
        ["source_quotation_id"], ["id"],
        source_schema="crm", referent_schema="crm", ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint("fk_sales_orders_source_quotation_id_quotations", "sales_orders", schema="crm", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_quotation_items_quotation_id'), table_name='quotation_items', schema='crm')
    op.drop_table('quotation_items', schema='crm')
    op.drop_index('ix_quotations_org_status', table_name='quotations', schema='crm')
    op.drop_table('quotations', schema='crm')
    # ### end Alembic commands ###
