"""M6 inventory

Revision ID: 0008_m6_inventory
Revises: 0007_m5_quotations
Create Date: 2026-08-26 10:10:41.471668
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0008_m6_inventory'
down_revision: str | None = '0007_m5_quotations'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code')),
    schema='crm'
    )
    op.create_table('stock_balances',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand >= 0', name=op.f('ck_stock_balances_on_hand_non_negative')),
    sa.CheckConstraint('reserved <= on_hand', name=op.f('ck_stock_balances_reserved_within_on_hand')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_stock_balances_reserved_non_negative')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_stock_balances_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['crm.warehouses.id'], name=op.f('fk_stock_balances_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_variant_id', name=op.f('pk_stock_balances')),
    schema='crm'
    )
    op.create_table('stock_movements',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('movement_type', sa.String(length=25), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('movement_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('opening', 'adjustment', 'delivery_out', 'delivery_reversal', 'receipt_in')", name=op.f('ck_stock_movements_type_valid')),
    sa.CheckConstraint('quantity <> 0', name=op.f('ck_stock_movements_quantity_non_zero')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_stock_movements_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['crm.warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    schema='crm'
    )
    op.create_index('ix_movements_variant_wh_time', 'stock_movements', ['product_variant_id', 'warehouse_id', 'movement_at'], unique=False, schema='crm')
    op.create_table('stock_reservations',
    sa.Column('sales_order_item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'released', 'fulfilled')", name=op.f('ck_stock_reservations_status_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_reservations_quantity_positive')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_stock_reservations_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['crm.sales_order_items.id'], name=op.f('fk_stock_reservations_sales_order_item_id_sales_order_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['crm.warehouses.id'], name=op.f('fk_stock_reservations_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reservations')),
    schema='crm'
    )
    op.create_index('ix_reservations_order_item', 'stock_reservations', ['sales_order_item_id', 'status'], unique=False, schema='crm')
    op.drop_constraint(op.f('fk_sales_orders_source_quotation_id_quotations'), 'sales_orders', schema='crm', type_='foreignkey')
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE VIEW crm.v_stock_available AS
        SELECT
            sb.warehouse_id,
            w.code AS warehouse_code,
            sb.product_variant_id,
            p.sku,
            p.name AS product_name,
            pv.variant_name,
            pv.variant_code,
            u.code AS uom_code,
            sb.on_hand,
            sb.reserved,
            (sb.on_hand - sb.reserved) AS available,
            sb.updated_at
        FROM crm.stock_balances sb
        JOIN crm.warehouses w ON w.id = sb.warehouse_id
        JOIN crm.product_variants pv ON pv.id = sb.product_variant_id
        JOIN crm.products p ON p.id = pv.product_id
        JOIN crm.units_of_measure u ON u.id = pv.uom_id;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS crm.v_stock_available")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_sales_orders_source_quotation_id_quotations'), 'sales_orders', 'quotations', ['source_quotation_id'], ['id'], source_schema='crm', referent_schema='crm', ondelete='RESTRICT')
    op.drop_index('ix_reservations_order_item', table_name='stock_reservations', schema='crm')
    op.drop_table('stock_reservations', schema='crm')
    op.drop_index('ix_movements_variant_wh_time', table_name='stock_movements', schema='crm')
    op.drop_table('stock_movements', schema='crm')
    op.drop_table('stock_balances', schema='crm')
    op.drop_table('warehouses', schema='crm')
    # ### end Alembic commands ###
