"""M7 invoices

Revision ID: 0009_m7_invoices
Revises: 0008_m6_inventory
Create Date: 2026-08-26 10:15:00.397284
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0009_m7_invoices'
down_revision: str | None = '0008_m6_inventory'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('origin', sa.String(length=15), server_default='system', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('system','migration')", name=op.f('ck_invoices_origin_valid')),
    sa.CheckConstraint("status IN ('draft', 'issued', 'cancelled')", name=op.f('ck_invoices_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_invoices_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['crm.sales_orders.id'], name=op.f('fk_invoices_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number')),
    schema='crm'
    )
    op.create_index('ix_invoices_org', 'invoices', ['organization_id'], unique=False, schema='crm')
    op.create_index('ix_invoices_status_due', 'invoices', ['status', 'due_date'], unique=False, schema='crm')
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_item_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('specification_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_invoice_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_invoice_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['crm.invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['crm.products.id'], name=op.f('fk_invoice_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_invoice_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['crm.sales_order_items.id'], name=op.f('fk_invoice_items_sales_order_item_id_sales_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False, schema='crm')
    # ### end Alembic commands ###

    # Placeholder balances view (allocated = 0). The M9 payments migration
    # replaces it with the allocation-aware version.
    op.execute("""
        CREATE OR REPLACE VIEW crm.v_invoice_balances AS
        SELECT
            i.id AS invoice_id,
            i.invoice_number,
            i.organization_id,
            i.status,
            i.invoice_date,
            i.due_date,
            i.grand_total,
            0::numeric(14,2) AS allocated,
            CASE WHEN i.status = 'issued' THEN i.grand_total ELSE 0::numeric(14,2) END AS outstanding,
            CASE
                WHEN i.status <> 'issued' THEN i.status
                WHEN i.due_date IS NOT NULL AND i.due_date < CURRENT_DATE THEN 'overdue'
                ELSE 'issued'
            END AS derived_status
        FROM crm.invoices i;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS crm.v_invoice_balances")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_invoice_items_invoice_id'), table_name='invoice_items', schema='crm')
    op.drop_table('invoice_items', schema='crm')
    op.drop_index('ix_invoices_status_due', table_name='invoices', schema='crm')
    op.drop_index('ix_invoices_org', table_name='invoices', schema='crm')
    op.drop_table('invoices', schema='crm')
    # ### end Alembic commands ###
