"""M8 deliveries

Revision ID: 0010_m8_deliveries
Revises: 0009_m7_invoices
Create Date: 2026-08-26 10:22:14.594352
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0010_m8_deliveries'
down_revision: str | None = '0009_m7_invoices'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('challan_number', sa.String(length=20), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_person', sa.String(length=150), nullable=True),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('challan_pdf_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'dispatched', 'delivered', 'cancelled')", name=op.f('ck_deliveries_status_valid')),
    sa.ForeignKeyConstraint(['branch_id'], ['crm.organization_branches.id'], name=op.f('fk_deliveries_branch_id_organization_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_deliveries_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['crm.sales_orders.id'], name=op.f('fk_deliveries_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['crm.warehouses.id'], name=op.f('fk_deliveries_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('challan_number', name=op.f('uq_deliveries_challan_number')),
    schema='crm'
    )
    op.create_index('ix_deliveries_order', 'deliveries', ['sales_order_id', 'status'], unique=False, schema='crm')
    op.create_index('ix_deliveries_status_scheduled', 'deliveries', ['status', 'scheduled_date'], unique=False, schema='crm')
    op.create_table('delivery_items',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_item_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=False),
    sa.Column('dispatched_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('rejection_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('delivered_quantity + rejected_quantity <= dispatched_quantity', name=op.f('ck_delivery_items_delivered_within_dispatched')),
    sa.CheckConstraint('delivered_quantity >= 0', name=op.f('ck_delivery_items_delivered_non_negative')),
    sa.CheckConstraint('dispatched_quantity >= 0', name=op.f('ck_delivery_items_dispatched_non_negative')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_delivery_items_rejected_non_negative')),
    sa.ForeignKeyConstraint(['delivery_id'], ['crm.deliveries.id'], name=op.f('fk_delivery_items_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['crm.product_variants.id'], name=op.f('fk_delivery_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['crm.sales_order_items.id'], name=op.f('fk_delivery_items_sales_order_item_id_sales_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_items')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False, schema='crm')
    op.create_table('proof_of_delivery',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('receiver_name', sa.String(length=150), nullable=False),
    sa.Column('receiver_designation', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_challan_document_id', sa.UUID(), nullable=True),
    sa.Column('signature_document_id', sa.UUID(), nullable=True),
    sa.Column('photo_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['crm.deliveries.id'], name=op.f('fk_proof_of_delivery_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_of_delivery')),
    sa.UniqueConstraint('delivery_id', name=op.f('uq_proof_of_delivery_delivery_id')),
    schema='crm'
    )
    # ### end Alembic commands ###

    # Reservations now track REMAINING quantity; 0 = fully fulfilled.
    op.execute(
        "ALTER TABLE crm.stock_reservations "
        "DROP CONSTRAINT ck_stock_reservations_quantity_positive"
    )
    op.execute(
        "ALTER TABLE crm.stock_reservations "
        "ADD CONSTRAINT ck_stock_reservations_quantity_positive CHECK (quantity >= 0)"
    )

    op.execute("""
        CREATE OR REPLACE VIEW crm.v_order_delivery_progress AS
        SELECT
            soi.id AS sales_order_item_id,
            soi.sales_order_id,
            so.order_number,
            soi.description_snapshot,
            soi.uom_code,
            soi.quantity AS ordered,
            COALESCE(d.delivered, 0) AS delivered,
            COALESCE(d.rejected, 0) AS rejected,
            soi.quantity - COALESCE(d.delivered, 0) AS remaining
        FROM crm.sales_order_items soi
        JOIN crm.sales_orders so ON so.id = soi.sales_order_id
        LEFT JOIN LATERAL (
            SELECT sum(di.delivered_quantity) AS delivered,
                   sum(di.rejected_quantity) AS rejected
            FROM crm.delivery_items di
            JOIN crm.deliveries dl ON dl.id = di.delivery_id
            WHERE di.sales_order_item_id = soi.id AND dl.status = 'delivered'
        ) d ON true;
    """)
    op.execute("""
        CREATE OR REPLACE VIEW crm.v_delivery_exceptions AS
        SELECT
            dl.id AS delivery_id,
            dl.challan_number,
            dl.sales_order_id,
            dl.organization_id,
            o.name AS organization_name,
            dl.status,
            dl.scheduled_date,
            (dl.status IN ('draft','dispatched')
                AND dl.scheduled_date IS NOT NULL
                AND dl.scheduled_date < now()) AS delayed,
            (dl.status = 'delivered' AND pod.id IS NULL) AS missing_pod,
            COALESCE(rej.rejected_total, 0) AS rejected_total
        FROM crm.deliveries dl
        JOIN crm.organizations o ON o.id = dl.organization_id
        LEFT JOIN crm.proof_of_delivery pod ON pod.delivery_id = dl.id
        LEFT JOIN LATERAL (
            SELECT sum(di.rejected_quantity) AS rejected_total
            FROM crm.delivery_items di WHERE di.delivery_id = dl.id
        ) rej ON true
        WHERE dl.status <> 'cancelled'
          AND (
            (dl.status IN ('draft','dispatched') AND dl.scheduled_date < now())
            OR (dl.status = 'delivered' AND pod.id IS NULL)
            OR COALESCE(rej.rejected_total, 0) > 0
          );
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS crm.v_order_delivery_progress")
    op.execute("DROP VIEW IF EXISTS crm.v_delivery_exceptions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proof_of_delivery', schema='crm')
    op.drop_index(op.f('ix_crm_delivery_items_delivery_id'), table_name='delivery_items', schema='crm')
    op.drop_table('delivery_items', schema='crm')
    op.drop_index('ix_deliveries_status_scheduled', table_name='deliveries', schema='crm')
    op.drop_index('ix_deliveries_order', table_name='deliveries', schema='crm')
    op.drop_table('deliveries', schema='crm')
    # ### end Alembic commands ###
