"""M9 payments

Revision ID: 0011_m9_payments
Revises: 0010_m8_deliveries
Create Date: 2026-08-26 10:26:35.383331
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0011_m9_payments'
down_revision: str | None = '0010_m8_deliveries'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_number', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('proof_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=25), server_default='recorded', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash', 'bank_transfer', 'cheque', 'online', 'other')", name=op.f('ck_payments_method_valid')),
    sa.CheckConstraint("status IN ('recorded', 'partially_allocated', 'allocated', 'reversed')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['crm.organizations.id'], name=op.f('fk_payments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('payment_number', name=op.f('uq_payments_payment_number')),
    schema='crm'
    )
    op.create_index('ix_payments_org', 'payments', ['organization_id', 'status'], unique=False, schema='crm')
    op.create_table('receipts',
    sa.Column('receipt_number', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pdf_document_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['crm.payments.id'], name=op.f('fk_receipts_payment_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_receipts_payment_id')),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_receipts_receipt_number')),
    schema='crm'
    )
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('allocated_amount > 0', name=op.f('ck_payment_allocations_amount_positive')),
    sa.ForeignKeyConstraint(['invoice_id'], ['crm.invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['crm.payments.id'], name=op.f('fk_payment_allocations_payment_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations')),
    sa.UniqueConstraint('payment_id', 'invoice_id', name='uq_allocation_payment_invoice'),
    schema='crm'
    )
    op.create_index('ix_allocations_invoice', 'payment_allocations', ['invoice_id'], unique=False, schema='crm')
    # ### end Alembic commands ###

    # Allocation-aware invoice balances (replaces the M7 placeholder).
    op.execute("""
        CREATE OR REPLACE VIEW crm.v_invoice_balances AS
        SELECT
            i.id AS invoice_id,
            i.invoice_number,
            i.organization_id,
            i.status,
            i.invoice_date,
            i.due_date,
            i.grand_total,
            COALESCE(a.allocated, 0)::numeric(14,2) AS allocated,
            CASE WHEN i.status = 'issued'
                 THEN (i.grand_total - COALESCE(a.allocated, 0))::numeric(14,2)
                 ELSE 0::numeric(14,2) END AS outstanding,
            CASE
                WHEN i.status <> 'issued' THEN i.status
                WHEN i.grand_total - COALESCE(a.allocated, 0) <= 0 THEN 'paid'
                WHEN COALESCE(a.allocated, 0) > 0 THEN 'partially_paid'
                WHEN i.due_date IS NOT NULL AND i.due_date < CURRENT_DATE THEN 'overdue'
                ELSE 'issued'
            END AS derived_status
        FROM crm.invoices i
        LEFT JOIN LATERAL (
            SELECT sum(pa.allocated_amount) AS allocated
            FROM crm.payment_allocations pa
            JOIN crm.payments p ON p.id = pa.payment_id
            WHERE pa.invoice_id = i.id AND p.status <> 'reversed'
        ) a ON true;
    """)
    op.execute("""
        CREATE OR REPLACE VIEW crm.v_receivables_aging AS
        SELECT
            b.invoice_id,
            b.invoice_number,
            b.organization_id,
            o.name AS organization_name,
            b.invoice_date,
            b.due_date,
            b.grand_total,
            b.allocated,
            b.outstanding,
            b.derived_status,
            GREATEST(0, (CURRENT_DATE - b.due_date))::int AS days_overdue,
            CASE
                WHEN b.due_date >= CURRENT_DATE THEN 'current'
                WHEN CURRENT_DATE - b.due_date <= 30 THEN '0-30'
                WHEN CURRENT_DATE - b.due_date <= 60 THEN '31-60'
                WHEN CURRENT_DATE - b.due_date <= 90 THEN '61-90'
                ELSE '90+'
            END AS bucket
        FROM crm.v_invoice_balances b
        JOIN crm.organizations o ON o.id = b.organization_id
        WHERE b.status = 'issued' AND b.outstanding > 0;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS crm.v_receivables_aging")
    # Restore the M7 placeholder version of the balances view.
    op.execute("""
        CREATE OR REPLACE VIEW crm.v_invoice_balances AS
        SELECT i.id AS invoice_id, i.invoice_number, i.organization_id, i.status,
               i.invoice_date, i.due_date, i.grand_total,
               0::numeric(14,2) AS allocated,
               CASE WHEN i.status = 'issued' THEN i.grand_total ELSE 0::numeric(14,2) END AS outstanding,
               CASE WHEN i.status <> 'issued' THEN i.status
                    WHEN i.due_date IS NOT NULL AND i.due_date < CURRENT_DATE THEN 'overdue'
                    ELSE 'issued' END AS derived_status
        FROM crm.invoices i;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_allocations_invoice', table_name='payment_allocations', schema='crm')
    op.drop_table('payment_allocations', schema='crm')
    op.drop_table('receipts', schema='crm')
    op.drop_index('ix_payments_org', table_name='payments', schema='crm')
    op.drop_table('payments', schema='crm')
    # ### end Alembic commands ###
