"""M12 import staging

Revision ID: 0012_m12_imports
Revises: 0011_m9_payments
Create Date: 2026-08-26 10:36:36.435501
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0012_m12_imports'
down_revision: str | None = '0011_m9_payments'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('entity_kind', sa.String(length=40), server_default='organizations', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending_review', nullable=False),
    sa.Column('source_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ready_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('imported_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'imported', 'discarded')", name=op.f('ck_import_batches_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    schema='crm'
    )
    op.create_table('import_rows',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('classification', sa.String(length=20), server_default='prospect', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='ready', nullable=False),
    sa.Column('imported_organization_id', sa.UUID(), nullable=True),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('ready', 'error', 'duplicate', 'imported', 'rejected', 'skipped')", name=op.f('ck_import_rows_status_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['crm.import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False, schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_import_rows_batch_id'), table_name='import_rows', schema='crm')
    op.drop_table('import_rows', schema='crm')
    op.drop_table('import_batches', schema='crm')
    # ### end Alembic commands ###
